services:
  master:
    image: apache/spark:3.5.5
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "7077:7077"
      - "8080:8080"
  worker:
    image: apache/spark:3.5.5
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
    depends_on:
      - master
