/* A prerequisite-led journey. Numbers and traces are teaching examples.
   Chapter files supply selected visual scenarios; this file owns the lesson text. */
(function () {
  const figure = (file, alt, caption) => `<figure class="mm"><img src="diagrams/${file}.svg" alt="${alt}" width="640" height="340"><figcaption>${caption}</figcaption></figure>`;
  const table = (caption, head, rows) => `<figure class="ds-table"><figcaption>${caption}</figcaption><div class="ds-scroll"><table><thead><tr>${head.map(x => `<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map((x, i) => i ? `<td>${x}</td>` : `<th scope="row">${x}</th>`).join('')}</tr>`).join('')}</tbody></table></div></figure>`;
  const section = (title, body) => `<h3>${title}</h3>${body}`;
  const chapters = [];
  function lesson(c) {
    const i = chapters.length;
    c.explain = `<div class="ds-bridge"><b>${c.phase}</b><p><b>Start here.</b> ${c.before}</p><p><b>By the end.</b> ${c.goal}</p></div>` + c.explain +
      section('Check your understanding', `<p>${c.check}</p><details class="ds-answer"><summary>Show the reasoning</summary><p>${c.answer}</p></details>`) +
      `<nav class="ds-next" aria-label="Learning journey">${i ? `<a href="#ch${i - 1}&view=explain">← Previous lesson</a>` : ''}<a href="#ch${i + 1}&view=explain">Next: ${c.next} →</a></nav>`;
    chapters.push(c);
  }

  lesson({
    title: 'Why use more than one machine?', phase: 'Part I · Machines and messages',
    before: 'You can read a function and know that a program uses CPU, memory and disk. No distributed systems vocabulary is assumed.',
    goal: 'Separate capacity, availability and latency, and identify which resource more machines would actually help.',
    problem: 'Our marketplace runs its checkout application and order database on one machine. More shoppers arrive than its CPU can handle. A faster machine helps for a while, but when it stops, every shopper loses access. We need to decide what adding a second machine should achieve.',
    predict: { q: 'We add another application server, but both servers still write to the same busy database. Which resource gained capacity?', opts: ['Application processing', 'The database write path', 'Every part of checkout equally'], ans: 0, why: 'Only the application processing was divided. Both application servers still wait for the same database.' },
    explain: section('1. Start with one request', `<p>A shopper clicks Buy. Application code checks the input and calculates a total. The database stores the order. The application sends a response. These are different pieces of work: CPU work, disk work and communication. A slow request is a symptom; it does not tell us which piece is full.</p><p><b>Capacity</b> is how much work a system can complete per unit of time. <b>Latency</b> is how long one request waits. <b>Availability</b>, in ordinary operational language, asks whether users can get a useful response. A second machine may help one of these goals without helping the others. Keep the goal explicit before picking a design.</p>`) +
    section('2. Scale up, then consider scale out', `<p><b>Scaling up</b> gives one machine more resources. Threads and asynchronous I/O can use those resources better: while one task waits for disk, another runs. Neither technique creates a second disk on another machine or preserves service when this entire machine fails.</p><p><b>Scaling out</b> distributes work over separate machines. A <b>load balancer</b> chooses which application server receives each request. If those servers do independent work, more servers can process more requests. If every request still needs one shared database, that shared resource can cap the total throughput.</p><p>For a toy capacity model, each app server can process 100 requests per second and the database can accept 150 writes per second. One server permits at most 100 completed checkouts per second. Two permit at most 150, and four still permit at most 150. These are illustrative upper bounds, assuming one write per checkout and no other costs.</p>`) +
    table('Capacity model: follow the limiting resource', ['App servers', 'App capacity / s', 'DB capacity / s', 'Checkout ceiling / s'], [['1', '100', '150', '100'], ['2', '200', '150', '150'], ['4', '400', '150', '150']]) +
    section('3. Extra capacity is not a surviving copy', `<p>Two application servers can keep the application tier running when one stops, provided requests can reach the other and it has enough spare capacity. But if both depend on one database, losing that database still stops checkout. An independent copy of the data addresses a different problem. We will build that copy in the replication lesson; adding app servers alone does not create it.</p><p>Machine boundaries also add travel. An async function frees its thread while it waits for a remote response, but the user still waits for the message to go out, be processed and return. Reducing the number of sequential remote calls can reduce latency even when the number of machines stays the same.</p>`) +
    section('4. Choose the next step from evidence', `<p>Measure busy resources and queue time. If the app CPU is full while the database has room, adding app capacity is plausible. If writes queue at the database, adding callers may only lengthen that queue. If a single machine failure stops all access, investigate a surviving copy and a recovery procedure. If most time is communication, examine placement and the number of round trips.</p><p>Distribution introduces messages and independent failures. It is a tool for a particular constraint, so our next lesson asks what changes when a function runs on another machine.</p>`),
    check: 'Four application servers are idle, but the database is at its write limit. Would eight app servers raise that limit?', answer: 'No. The database is the shared limiting resource. First investigate its write workload and queue; changing data placement comes later.', next: 'Separate processes and partial failure',
    diagnose: [{t:'More callers, the same queue',sym:'App capacity rises but completed checkouts stay flat.',why:'The database write path is shared.',fix:['Compare queue time and resource utilization at each tier.','Change the saturated resource before adding callers.']}]
  });

  lesson({
    title: 'Separate processes and partial failure', phase: 'Part I · Machines and messages',
    before: 'The previous lesson separated application work from storage work. Now we put those parts on different machines.',
    goal: 'Explain what crosses a process boundary, and why an unanswered request does not prove the remote process has stopped.',
    problem: 'The checkout process runs on machine A and inventory runs on B. Checkout is healthy, but a request to inventory returns no answer. Inventory may be down, busy, unreachable, or already finished with its reply delayed. Checkout has to act with incomplete knowledge.',
    predict: {q:'A is running and cannot reach B. What do we know about B?',opts:['B has crashed','B is definitely still running','A has no timely response; B’s state is uncertain'],ans:2,why:'Silence can come from B, the network, or the returning response. A observes silence, not the cause.'},
    explain: section('1. What is a distributed system?', `<p>A <b>process</b> is a running program with its own memory. A <b>node</b> is a participating machine or service instance; we will say which meaning matters in an example. A distributed system has cooperating processes that communicate across boundaries. Each process knows its local state directly. It learns another process’s state through messages.</p><p>A local function can receive a pointer to an object in the same address space. A remote process cannot follow that pointer into another machine’s memory. The sender must encode the necessary data into bytes. The receiver decodes those bytes and performs its own work. A reply is another message, not a shared variable changing instantly.</p>`) +
    figure('process-boundary','Separate processes exchange request and reply bytes between independent memories.','The boundary is the new idea: local state is direct knowledge; remote state arrives through messages.') +
    section('2. Trace a healthy message exchange first', `<ol><li>Checkout A builds a request: reserve one item for order 42.</li><li>A encodes the request and sends it to inventory B.</li><li>B receives it, checks its own inventory and records a reservation.</li><li>B encodes a reply saying whether the reservation succeeded.</li><li>A receives the reply and continues checkout.</li></ol><p>Sending is not receiving. Receiving is not finishing. Finishing is not the same as the caller learning the result. These distinctions explain most surprises in the next lesson.</p>`) +
    section('3. Failure can be partial', `<p><b>Partial failure</b> means one part can fail while others keep running. A may be healthy while B has crashed. Both may be healthy while communication between them is broken. Or B may stop processing temporarily because it is overloaded or paused. A local inspection of A cannot tell these situations apart.</p><p>A <b>network partition</b> is a communication break that prevents some participants from reaching others. It need not split the whole system neatly in half. Communication can be asymmetric, and clients may still reach a server that its peers cannot reach. This use of “partition” means a broken network; later, a “data partition” means a subset of records.</p>`) +
    section('4. A timeout limits waiting, not uncertainty', `<p>A <b>timeout</b> is the caller’s decision to stop waiting after a chosen duration. It says the response did not arrive in time. It does not undo B’s reservation, prove B is dead, or prove the request never arrived. A caller can return an error while the remote operation continues.</p><p>Separate observations from conclusions in a trace. “No response by 3 seconds” is an observation. “Inventory did no work” is a conclusion requiring more evidence. Request identifiers and server-side records can help investigate the result, though those records also have to be reached over the network.</p><p>We assume ordinary crash and communication failures in this course. Malicious participants need additional protocols and are outside these examples. Our immediate challenge is simpler: what should A do after an ambiguous timeout?</p>`),
    check:'B reserved the item, but the reply is lost. Does A’s timeout release that item?',answer:'No. The reservation exists in B’s local state. A needs a protocol to discover, retry or cancel it; its local waiting limit cannot reverse remote work.',next:'Remote calls, retries and idempotency',
    diagnose:[{t:'Treating silence as a known outcome',sym:'A timeout is logged as “reservation failed,” but the reservation exists.',why:'The reply path failed after the operation finished.',fix:['Record the timeout as an unknown remote outcome.','Carry an operation identifier into the next recovery step.']}]
  });

  lesson({
    title:'Remote calls, retries and idempotency',phase:'Part I · Machines and messages',
    before:'You know requests and replies travel separately, and a timeout leaves the remote outcome uncertain.',goal:'Retry one logical operation without applying its business effect twice, and keep retry load within a deadline.',
    problem:'Checkout calls the payment service for order 42. Payment charges the card, but its reply is lost. Retrying seems sensible, yet a second charge would be wrong. We need a way to distinguish a repeated delivery from a new payment.',
    predict:{q:'After a timeout, which identifier should a retry carry?',opts:['A new payment identifier for each attempt','The same identifier for the same logical payment','No identifier; the timeout canceled the charge'],ans:1,why:'The operation identifier represents the payment intent. An attempt identifier can change for tracing, but retries must preserve the payment identity.'},
    explain:section('1. RPC is a request/reply protocol',`<p><b>RPC</b> means remote procedure call. Client code encodes a function name and arguments into a request; server code decodes it and invokes an operation. A reply carries a result or error. An interface description defines the fields both sides understand. RPC makes remote calls convenient to write, but it cannot remove the partial failures from the previous lesson.</p><p>Consider a request that never arrives, one that arrives and fails before charging, and one that charges successfully but loses its reply. The caller can see the same timeout in all three cases. Without additional information it cannot safely interpret silence as either success or failure.</p>`) +
    table('One timeout, different remote outcomes',['Failure point','Payment effect','Caller sees'],[['Request lost','No charge','Timeout'],['Server stops before charging','No charge','Timeout'],['Reply lost after charging','Charge completed','Timeout']]) +
    section('2. Define one logical operation',`<p>Generate a payment identifier, such as <code>pay-order-42</code>, before the first attempt. Send it with the order, amount and currency. The payment service stores that identity with the outcome. If the same identity arrives again, it returns the recorded outcome rather than starting another charge.</p><p>This is <b>idempotency</b>: repeated execution of the same logical operation has the intended effect of one execution. A natural operation such as “set title to Lead” can be idempotent by itself. “Subtract 10” is not; it needs a remembered identity or another way to prevent repeating the subtraction.</p>`) +
    section('3. The identity and effect must be coordinated',`<p>A naive implementation checks a key, charges, then stores the result. Two concurrent attempts can both see no key and both charge. A crash between the charge and recording the result creates the same gap. The deduplication record and effect must be coupled by the service’s transaction or by an idempotent protocol with the external provider.</p><pre>logical payment: pay-order-42\nattempt 1: same payment id → charge + record result\nattempt 2: same payment id → return recorded result</pre><p>Reject reuse of an identity with different parameters. Decide how long identities remain valid; after a deduplication record expires, replay may become unsafe. A timeout still means the caller may need to query the payment’s status rather than invent a fresh identity.</p>`) +
    section('4. Retries need a budget',`<p>Retrying improves the chance of delivering work, but it increases load. If three layers each make three attempts, one user operation can generate up to 27 calls at the bottom. During overload this can delay recovery. Assign one overall deadline, propagate the time remaining, and limit which layer retries.</p><p><b>Backoff</b> spaces attempts farther apart. <b>Jitter</b> varies that delay so many clients do not retry together. Neither creates extra capacity; they reduce synchronized pressure. Retry only errors the protocol considers retryable, and stop when the deadline or attempt budget is exhausted.</p><p>“At least once” describes possible repeated delivery. “At most once” describes avoiding repeated execution, possibly at the cost of missing work. A claim of exactly once must state the effect and failure boundary it covers. Next we move from one uncertain remote operation to keeping a second copy of data.</p>`),
    check:'A retry uses the same key, but the charge and key record are separate writes. What crash window remains?',answer:'The charge may complete before the key record is written. After a crash the retry sees no record and could charge again. Couple the identity to the effect or use the provider’s own idempotency protocol.',next:'Replication: building a second copy',
    source:{label:'gRPC: deadlines and propagation',href:'https://grpc.io/docs/guides/deadlines/'},
    diagnose:[{t:'Duplicate business effects',sym:'Two charges have different attempt IDs for the same order.',why:'Attempt identity was mistaken for payment identity.',fix:['Preserve the logical operation ID across retries.','Make deduplication and the effect atomic within their promised boundary.']}]
  });

  lesson({
    title:'Replication: building a second copy',phase:'Part II · Copies and data placement',
    before:'You can trace a message from one process to another. We now use messages to copy a record.',goal:'Define replica, leader, follower and replication log, and trace a healthy write before studying lag or failure.',
    problem:'The marketplace’s order store has one machine and one disk. If that disk becomes unavailable, nobody can read their orders. We add machine B, but simply installing the database on B does not copy existing orders or future changes. What protocol keeps it useful?',
    predict:{q:'A has orders 41 and 42. For B to be a replica of this data, what should B hold after it catches up?',opts:['Only order 41, so the records are divided','The same logical orders 41 and 42','Just the addresses of orders on A'],ans:1,why:'Replication creates copies of the same logical data. Dividing different records between machines is partitioning, introduced later.'},
    explain:section('1. A replica is a copy on another participant',`<p><b>Replication</b> keeps the same logical data on multiple participants. Each participant holding a copy is a <b>replica</b>. In our example A and B have separate disks and memories. Updating A does not magically update B; the change must cross the network and be applied there.</p><p>A second copy can let another machine serve reads or help recover when one machine stops. It also uses extra storage and communication. Two copies of a 100 GB dataset still represent 100 GB of distinct records, while consuming roughly 200 GB before logs and overhead. Copies do not by themselves divide the writing workload.</p>`) +
    figure('replication-copy','Leader A sends log entry 3 to follower B; both copies hold title Lead after replay.','Read the healthy path first: the same change is stored on two independent machines.') +
    section('2. Give writes one initial entry point',`<p>In <b>single-leader replication</b>, one replica accepts the writes for a dataset. That replica is the <b>leader</b>, also called the primary. Other replicas follow its changes and are called <b>followers</b>. A leader is a role in a protocol, not a more powerful kind of hardware.</p><p>Suppose the profile title is Engineer on both machines. A client asks A to set it to Lead. A records the change and sends it to B. B applies it to its own copy. Now both can answer Lead. This is the normal case; we have not crashed anything or routed a read too early.</p>`) +
    section('3. Use a log to describe ordered changes',`<p>A <b>replication log</b> is an ordered record of changes or commands. It is not merely a human-readable debug log. Here entry 1 creates the profile, entry 2 sets Engineer, and entry 3 sets Lead. A log position identifies progress within this one history. Position 3 means “up through the third entry,” not “three seconds.”</p><ol><li>The leader appends entry 3 to its log.</li><li>It makes the local change according to its storage rules.</li><li>It sends entry 3 to the follower.</li><li>The follower receives and stores the entry.</li><li>The follower applies the entry to its own data.</li></ol><p>Receiving, storing and applying are separate stages. A follower may have received an entry without making it visible to reads. Protocols choose which stage an acknowledgment confirms; later lessons will make this choice explicit.</p>`) +
    section('4. Copy the starting state as well as future changes',`<p>If B joins after years of writes, it needs a starting copy. A <b>snapshot</b> captures the dataset at a known log position. B installs that snapshot, then replays later entries. The snapshot and log positions must agree so B neither skips a change nor applies it incorrectly twice. The initial transfer can take substantial time and bandwidth.</p><p>A live replica is different from a backup. A backup preserves a recovery point; a replica tries to follow ongoing changes. If a mistaken delete is replicated, both live copies may lose the record. Recovery from mistakes still needs retained history or backups.</p><p>Two replicas also need suitably independent failure domains. Two processes on the same physical disk do not protect against losing that disk. For now, we know what a copy is and how it is built. Next we read during the gap between a leader changing and a follower applying that change.</p>`),
    check:'B has received entry 3, but its query table is still at entry 2. Can it already return the new title?',answer:'Not through that table. Receipt is not application. A read needs the follower’s applied state to include entry 3, or it must use another replica that does.',next:'Replication lag and session guarantees',
    source:{label:'PostgreSQL replication overview: shipping and replaying changes',href:'https://www.postgresql.org/docs/current/warm-standby.html'},
    diagnose:[{t:'An installed server is mistaken for a usable copy',sym:'The new machine starts but has missing orders.',why:'It has neither a consistent starting snapshot nor all later changes.',fix:['Install a snapshot at a recorded position.','Replay the later changes and verify progress before serving reads.']}]
  });

  lesson({
    title:'Replication lag and session guarantees',phase:'Part II · Copies and data placement',before:'A follower receives and applies an ordered log. Its data can be behind the leader between those steps.',goal:'Connect replication progress to what a reader sees, and distinguish read-your-writes from monotonic reads.',
    problem:'Alice saves her title as Lead and receives OK. Her reload goes to a follower that has not applied the update, so it shows Engineer. Nothing was deleted: two reads reached different points in the same history.',
    predict:{q:'The update is entry 812. Which follower can satisfy a read requiring Alice’s update?',opts:['Any follower with the request in its network buffer','A follower whose applied position is at least 812','The follower with the fastest response, regardless of position'],ans:1,why:'The read needs applied state that includes the update. A fast response from an earlier state is still stale.'},
    explain:section('1. Lag is a gap in progress',`<p><b>Replication lag</b> is the gap between the leader’s progress and a follower’s progress. In this lesson we compare applied log positions. The leader has applied through 812; follower 1 through 811; follower 2 through 809. Follower 2 is three entries behind. This count alone does not tell us how many seconds behind it is, because entries need not arrive at a constant rate.</p><p>A read from position 809 returns the state after entries up through 809. It can be internally correct and still omit a newer update. This is a <b>stale read</b>: a response reflecting an older state than the operation requires. A response labeled OK must be interpreted using the write protocol’s promise, rather than assuming every follower already applied it.</p>`) +
    table('Progress is more precise than “the replica is healthy”',['Participant','Applied position','Can include write 812?'],[['Leader','812','Yes'],['Follower 1','811','No'],['Follower 2','809','No']]) +
    section('2. Follow one writer’s next read',`<p><b>Read-your-writes</b> means a session’s later reads include its own completed writes. Alice’s client records the position returned by her write: 812. On reload it asks for a copy that has applied at least that position. The service can wait for a follower, route to a sufficiently advanced replica, or fail within its deadline if the requirement cannot be met.</p><p>The token belongs to a specific history. After a leadership change or across shards, a bare integer is not necessarily comparable. A real protocol needs the corresponding dataset and history identity, and sometimes a token for each relevant shard. Our tank visualization deliberately follows one unchanged log so the relationship is easy to see.</p>`) +
    section('3. Follow one reader across several reads',`<p><b>Monotonic reads</b> mean that once a session has observed some progress, later reads do not go backward in that history. Bob reads comments through position 701 from follower A. His next read goes to follower B at 690. Old comments reappear and new ones vanish. Bob did not write anything; read-your-writes alone does not cover this case.</p><p>Record the highest observed position and request at least that progress on subsequent reads. Sticky routing to one follower can help, but rerouting and failover still need a rule that preserves the minimum. If progress cannot be reached before the deadline, be explicit about the resulting wait or failure.</p>`) +
    section('4. Set the promise per operation',`<p>An eventually updated product description may tolerate a stale read. A user confirming their own edit usually expects read-your-writes. A shared stock reservation may need stronger coordination than either session promise. Choose a guarantee from the operation’s meaning instead of giving every read the same route.</p><p>Waiting for follower application trades freshness for latency and possibly availability. Reading the current leader may also help, but identifying a currently authoritative leader is its own problem, explored later. A synchronous acknowledgment of stored data does not automatically mean that any follower can serve it from its applied query state.</p><p>Measure gaps at the stages that matter: bytes sent, entries received, entries durably stored and entries applied. A follower with enough network bandwidth can still be slow at replay. Next we ask what a write acknowledgment promises if the leader fails before copying completes.</p>`),
    check:'Bob never writes, but his second read omits comments shown by his first read. Which promise is missing?',answer:'Monotonic reads. His session must not move to an earlier applied position. Read-your-writes concerns Bob’s own writes and does not address this example.',next:'Acknowledgments, leaders and failover',
    diagnose:[{t:'Saved, then old again',sym:'A reload shows an older value immediately after saving.',why:'The read route ignores the write’s required progress.',fix:['Return and carry a dataset-specific progress token.','Wait, route or return a bounded failure when no copy meets it.']}]
  });

  lesson({
    title:'Acknowledgments, leaders and failover',phase:'Part II · Copies and data placement',before:'Replicas are copies with separate progress. A read sees the entries its replica has applied.',goal:'State an acknowledgment’s durability promise, trace a surviving copy, and explain why choosing a replacement leader needs more than a timer.',
    problem:'The leader stores order 42 and immediately answers OK. Before a follower stores it, the leader’s disk becomes unreadable. A follower is promoted, but it has no order 42. The shopper has a receipt for data absent from every surviving copy.',
    predict:{q:'If OK means only “stored on the leader,” what can happen when that disk is lost before replication?',opts:['The receipt guarantees a surviving copy','The acknowledged order can be absent from surviving replicas','Every follower reconstructs it from the receipt automatically'],ans:1,why:'An acknowledgment cannot promise a second copy unless the protocol actually waited for that copy at the required storage stage.'},
    explain:section('1. Define the acknowledgment boundary',`<p>An <b>acknowledgment</b>, abbreviated ACK, is a protocol message confirming a specified step. A database might confirm receipt, local durable storage, follower durable storage, or application. These promises differ. Ask what OK means before using it as evidence that an order survives a particular failure.</p><p>In <b>asynchronous replication</b>, the leader can reply before followers confirm the change. This reduces waiting, but leaves an interval when only the leader has it. If that sole copy is lost, the acknowledged data can be lost. If the leader merely restarts with its intact log, the data may instead be recoverable. The failure scenario must state which storage survived.</p>`) +
    figure('ack-boundary','Asynchronous OK precedes a second copy; waiting for follower storage moves OK after that copy.','The same write has a different survival promise depending on where OK appears on the timeline.') +
    section('2. Wait for a specified copy',`<p>A protocol can delay OK until a follower confirms durable storage. Our example waits for one follower, so there are two stored copies before replying. It adds follower and network waiting to the write path. If no required follower can respond, the protocol must wait, reject, or explicitly weaken its durability promise; silently falling back changes what users were told.</p><p>This protects the example’s order against loss of the leader alone, assuming the acknowledging follower’s copy survives. It does not protect against both copies failing or authorize every follower to become leader. A follower that never received the order is still unsafe for this particular acknowledged history.</p>`) +
    section('3. Failover is a controlled role change',`<p><b>Failover</b> replaces a failed or unreachable serving participant. For single-leader writes, it means giving the leader role to an eligible replica and routing clients there. First detect a lack of timely responses. Then establish which replica can preserve the promised data, prevent conflicting authority, and let the other copies follow the accepted history.</p><p>In the ruler example every surviving log is a prefix of one former leader’s history. B ends at position 100 and A at 97, so B preserves more of that history. Comparing positions is useful under that stated assumption. In a general system, the longest log may contain uncommitted or conflicting entries. Terms, commitment and election rules matter; consensus will explain them.</p>`) +
    section('4. Silence does not revoke the old leader',`<p>The old leader may be isolated rather than dead. If another leader is chosen while the old one still accepts writes, the system has competing leaders, often called <b>split brain</b>. Merely changing a client address or writing a new leader name does not stop delayed operations from the old process.</p><p>We will handle authority with fencing and consensus after studying clocks and consistency. At this point keep two questions separate: which data must survive, and which participant may still act? A correct replacement procedure answers both.</p><p>Operationally record the acknowledged durability level, the surviving logs and the recovery choice. Measure recovery time as well as possible data loss. A recovery that completes quickly by discarding confirmed orders may violate the goal. Next we address a different constraint: how to split distinct records when one leader cannot hold or process all the data.</p>`),
    check:'A and B stored the order before OK, but failover promotes C, which never stored it. Was waiting for B enough to make this recovery safe?',answer:'No. The order survives on B, but the recovery ignored that copy. Durability and leader selection must work together. Waiting for one follower does not make any replacement safe.',next:'Partitioning: splitting distinct records',
    diagnose:[{t:'A receipt outlives every surviving copy',sym:'Order lookup returns not found after failover.',why:'The acknowledgment boundary and recovery procedure did not preserve the promised history.',fix:['Establish which storage stage each ACK confirms.','Select a replacement using the protocol’s durability and authority rules.']}]
  });

  lesson({
    title:'Partitioning: splitting distinct records',phase:'Part II · Copies and data placement',before:'Replication copies records for survival and reads. It does not necessarily divide one dataset’s writes among leaders.',goal:'Distinguish partitioning from replication, route a key to its owner, and recognize a hot key versus uneven placement.',
    problem:'All sellers’ orders still go through one write owner. That machine is full, though the system has several copies. We want different machines to own different sellers’ orders, then give each owned subset its own replicas.',
    predict:{q:'A stores seller 1’s orders; B stores seller 2’s orders, with no extra copies. What did we create?',opts:['Two replicas of the whole dataset','Two data partitions without redundancy','A network partition'],ans:1,why:'The records were divided, not copied. Losing A still loses access to seller 1’s orders unless that subset has another copy.'},
    explain:section('1. Divide the dataset by a key',`<p><b>Partitioning</b> divides records into subsets. A <b>shard</b> is a subset assigned to an owner in the system. The <b>partition key</b> is the record field used to choose that subset. For our marketplace, seller ID is one possible choice: records for different sellers can go to different owners.</p><p>Partitioning and replication are independent axes. We can split records across A and B, then copy A’s shard to C and B’s shard to D. This adds capacity for distinct records and surviving copies for each subset. A client still needs to find the owner of the requested key.</p>`) +
    figure('copy-vs-split','Replication copies orders 1 and 2 to both machines; partitioning places order 1 on A and order 2 on B.','Different records create capacity; copies create redundancy. A production layout often combines both.') +
    section('2. Choose a placement rule',`<p><b>Hash partitioning</b> computes a stable number from the key and assigns it to a shard. With the simple rule <code>hash(key) % N</code>, different keys tend to spread across N owners. Changing N changes many assignments, so adding a server may require moving a large fraction of records.</p><p>Consistent hashing assigns ranges in a stable hash space and changes a subset of ownership on membership changes. Directory-based placement instead looks up a shard assignment. Both require a movement protocol, ownership metadata and routing that survives the transition; a clever mapping function alone does not copy the data.</p><p><b>Range partitioning</b> groups ordered keys, such as seller IDs 1–1000. It supports targeted range reads, but monotonically increasing keys can direct most new inserts to the final range. The best choice depends on query access and the distribution of work, not just the number of records.</p>`) +
    section('3. An even key count can hide uneven work',`<p>A shard with many rarely used sellers may be quiet. One famous seller can generate most of the requests. This is a <b>hot key</b>. Hashing distributes different keys; it cannot divide one key’s workload if all of that key must stay together. Adding nodes does not necessarily help its owner.</p><p>A bucket can make the effective key <code>(seller_id, bucket)</code>. If requests are spread across several buckets, the seller’s work can use several owners. The cost is that a query for all of that seller’s orders must locate and combine those buckets. A bucket chosen by the current day does not spread one busy day’s writes; choose the bucket from the actual workload.</p>`) +
    section('4. Movement and queries expose the boundaries',`<p>Moving a shard means copying its state while handling ongoing writes, then changing the authoritative route at a defined point. During the move, routers may hold old metadata. The protocol needs a forwarding, retry or version rule so writes are neither dropped nor accepted by conflicting owners.</p><p>Queries that cross shards perform several reads and combine results. Transactions that modify several shards need a coordination protocol, covered later. Keep commonly related work together when possible, while avoiding a key so large that it defeats scaling.</p><p>Measure bytes, request rates, queue time and CPU per shard. Equal storage size is not evidence of equal load. Our next lesson asks how to order changes when timestamps from different machines disagree, before we allow multiple write entry points.</p>`),
    check:'One seller causes 70% of writes under one partition key. Will adding another replica automatically divide those writes?',answer:'No. Extra copies do not divide that logical key’s ownership. The data model or ownership protocol needs a deliberate way to spread its work.',next:'Clocks, causality and logical order',
    diagnose:[{t:'Balanced storage, one overloaded owner',sym:'One shard has high queue time while peers have room.',why:'A hot key dominates requests despite an even count of records.',fix:['Measure request rates per key and shard.','Choose bounded buckets only after checking the queries and load they create.']}]
  });

  lesson({
    title:'Clocks, causality and logical order',phase:'Part III · Ordering and consistency',before:'Each machine has local state and sends messages. Different shards or replicas may produce changes independently.',goal:'Distinguish wall time from causal order and use a logical counter without treating it as a perfect history of causes.',
    problem:'Alice sends a question at 12:00:05 on her machine. Bob’s slower clock labels receipt at 12:00:02. Sorting by these times makes the receipt appear before the send, even though Bob could not receive a message before Alice sent it.',
    predict:{q:'The receive timestamp is earlier than the send timestamp. Which fact still holds?',opts:['The receive caused the send','The send happened before this receive','The two events must be unrelated'],ans:1,why:'The message itself proves a causal relationship. Clock labels do not reverse that relationship.'},
    explain:section('1. Physical clocks measure imperfect time',`<p>A <b>wall clock</b> estimates a date and time. Machines can disagree because of drift and synchronization error. Corrections may move a clock forward or backward. Two timestamps with different values are therefore not enough to prove the real order of events on different machines.</p><p>Use wall time for calendars and human-facing records, with appropriate uncertainty. For elapsed time within one process, a <b>monotonic clock</b> avoids ordinary wall-clock adjustments. It still does not give two processes a shared event order or make a paused worker safe to write.</p>`) +
    figure('causal-order','A question sent at wall time 12:00:05 arrives at a receiver showing 12:00:02; the send still precedes receipt.','The message establishes cause and effect even when the wall-clock readings disagree.') +
    section('2. Build a partial order from evidence',`<p>We write <code>a → b</code> when event a <b>happened before</b> event b. Events have local program order; sending a particular message precedes receiving it; and these relationships chain together. If Alice asks, Bob receives, then Bob answers, the question precedes the answer.</p><p>Some events have no observed causal path either way. They are <b>concurrent</b> in this model. This does not require equal clock times or literal simultaneity. It means the known message and process history does not order them. Two people editing a title without seeing each other’s change are an important example.</p>`) +
    section('3. Count progress with a logical clock',`<p>A <b>Lamport clock</b> is a counter maintained by each process. Increment it for a local event, attach it to outgoing messages, and on receipt update the local counter to greater than both its current value and the received value. In a toy trace A sends with counter 4; B is at 1, receives 4 and moves to 5.</p><p>The useful direction is: if a happened before b, a’s logical counter is smaller. The reverse is false. A counter of 4 on one process and 5 on an unrelated process does not prove a message path between them. Adding a process identifier can break ties for a deterministic total order, but that tie-breaker is a policy rather than discovered causality.</p>`) +
    section('4. Track what an update has seen',`<p>A <b>version vector</b> tracks progress from several writers. In a simplified two-writer model, <code>[2,1]</code> includes more known progress than <code>[1,1]</code>. But <code>[2,1]</code> and <code>[1,2]</code> each contain progress the other lacks; neither dominates. They represent concurrent versions that may need merging.</p><p>Vectors store more metadata than one timestamp and require rules for writer identities and membership changes. They are useful when the application needs to detect concurrency rather than silently pick a winner. The exact representation depends on the protocol.</p><p>These tools answer different questions: wall time labels dates; monotonic time measures local waiting; logical clocks reflect constraints on event order; vectors can detect concurrent versions in their defined model. Next we use this distinction to examine replicas that accept writes through multiple entry points.</p>`),
    check:'Lamport(a) = 4 and Lamport(b) = 5. Does that prove a caused b?',answer:'No. Happened-before implies increasing Lamport values, but increasing values do not imply happened-before. The events may be concurrent.',next:'Leaderless writes, conflicts and quorums',
    source:{label:'Lamport: Time, Clocks, and the Ordering of Events in a Distributed System',href:'https://lamport.azurewebsites.net/pubs/time-clocks.pdf'},
    diagnose:[{t:'A timestamp is mistaken for proof of causality',sym:'An edit that did not see another edit is treated as its successor.',why:'A scalar clock creates an order without detecting every concurrent update.',fix:['Identify the ordering guarantee the application needs.','Use causal metadata or an explicit merge rule when concurrent changes matter.']}]
  });

  lesson({
    title:'Leaderless writes, conflicts and quorums',phase:'Part III · Ordering and consistency',before:'Replicas are copies, data partitions divide records, and independent updates can be concurrent even with different timestamps.',goal:'Define a quorum as a selected set of responses, prove read/write overlap under stated assumptions, and explain why overlap alone is not linearizability.',
    problem:'The cart store lets a coordinator send a change to several replicas without one fixed write leader. It answers after one replica stores the cart. A later read asks a different replica and finds the old cart. We need rules for both response sets and conflicting versions.',
    predict:{q:'For a fixed replica set {A, B, C}, a write reaches two members and a read queries two. Must the two sets intersect?',opts:['Yes, at least one member is shared','No, they can be disjoint','Only if their physical clocks agree'],ans:0,why:'Two disjoint sets of two would require four distinct members, but the fixed set has only three. This is a set argument, not yet a complete correctness proof.'},
    explain:section('1. Accept writes through several entry points',`<p>In a <b>leaderless</b> design a client or coordinator contacts a record’s replica set rather than always sending its write through a single designated leader. Several copies can receive operations independently. The protocol must decide when to answer and how to reconcile versions that differ.</p><p>Let <code>N</code> be the size of a fixed replica set, <code>W</code> the number of required write acknowledgments, and <code>R</code> the number of required read responses. A <b>quorum</b> here is a response set satisfying the operation’s threshold. This use of quorum does not necessarily mean a majority: R and W can differ.</p>`) +
    table('N = 3: examine the actual sets',['Write set','Read set','Overlap?'],[['{A}, W = 1','{B}, R = 1','None'],['{A, B}, W = 2','{B, C}, R = 2','B'],['{A, C}, W = 2','{A, B}, R = 2','A']]) +
    section('2. Prove overlap, then ask what it gives',`<p>With a fixed set of N members, <code>R + W &gt; N</code> forces every such read set to intersect every such write set. The overlapping member can contribute the completed write’s version if it retained that version and the read protocol retrieves and resolves it correctly.</p><p>We first reason about one completed write, no concurrent updates, unchanged membership and the same home replica set. Under these assumptions, fetching enough copies and selecting the appropriate version can avoid the missed-write example. Concurrent writes, incomplete operations and membership changes introduce additional cases.</p><p><b>Sloppy quorums</b> may temporarily acknowledge writes on substitute nodes outside the home replica set. Numeric thresholds alone then do not prove that a home-set read reaches the acknowledged data. Hints and repair can move copies back later, but “eventually copied” and “visible to this read now” are different promises.</p>`) +
    section('3. Overlap does not choose the correct version',`<p>If Alice and Bob edit independently, both versions may be present. <b>Last-write-wins</b> chooses the version with the largest timestamp according to a specified ordering rule. A fast clock can win even when the human edit happened earlier, and one edit disappears. A tie-breaker makes selection deterministic; it does not preserve both intentions.</p><p>A causal version can distinguish a successor from a concurrent edit. The application might merge cart items, preserve both versions for a user decision, or reject one update through stronger coordination. The right rule depends on the meaning of the data. Combining sets is plausible for some carts but does not safely merge arbitrary bank withdrawals.</p>`) +
    section('4. Repair and availability have costs',`<p><b>Read repair</b> can update stale copies while reading. Background anti-entropy compares participants and repairs differences over time. Temporary hints remember work for an unavailable home replica. These mechanisms help copies converge; none should be confused with a guarantee that every immediate read is fresh.</p><p>Higher thresholds require more responding participants and can add waiting. Lower thresholds allow more operations during outages but permit more missed or conflicting versions. Choose using the required effect, then inspect the complete algorithm. In particular, the inequality alone does not prove linearizability. The next lesson defines that stronger user-visible promise directly.</p>`),
    check:'W = 2 and R = 2, but the write ACKs came from substitute nodes while the read uses the three home nodes. Does the usual overlap proof apply?',answer:'No. The proof assumes both response sets are subsets of the same fixed set. Substitute nodes break that assumption.',next:'Consistency contracts and linearizability',
    source:{label:'Dynamo: replica sets, quorum parameters and conflict resolution',href:'https://www.allthingsdistributed.com/files/amazon-dynamo-sosp2007.pdf'},
    diagnose:[{t:'Thresholds are treated as a complete proof',sym:'A confirmed write is absent from a read despite apparently sufficient R and W.',why:'The sets or version-resolution assumptions differ from the textbook example.',fix:['Trace the actual ACK and read responders.','Check membership, incomplete writes and version resolution before claiming a guarantee.']}]
  });

  lesson({
    title:'Consistency contracts and linearizability',phase:'Part III · Ordering and consistency',before:'You have seen stale reads, session progress and overlapping replica response sets. Now define the promise from the user’s operation history.',goal:'Explain linearizability using invocation and response intervals, and distinguish it from session guarantees and transaction isolation.',
    problem:'The stock counter is updated to zero and the operation completes. A different shopper starts a read afterward and sees one item remaining. Both calls succeeded, but the behavior does not match one current shared counter.',
    predict:{q:'A write of x = 2 completes before a read starts. With no later write, what must a linearizable read return?',opts:['1 or 2 depending on its replica','2','Any value if the system eventually converges'],ans:1,why:'Real-time precedence is part of the contract. A completed write precedes a later non-overlapping read in the apparent single-object history.'},
    explain:section('1. Begin with an operation history',`<p>A client <b>invokes</b> an operation, then later receives its <b>response</b>. The interval between those points matters. For one register x, imagine a write that sets x to 2. If it finishes before another client begins a read, the write comes first in real time. If the intervals overlap, either operation may be ordered first, as long as the complete history remains valid.</p><p><b>Linearizability</b> means each operation appears to take effect at one point between its invocation and response, and all operations on the object fit a legal sequential history respecting this real-time precedence. It is a behavioral contract, not a requirement that only one physical copy exists.</p>`) +
    figure('read-interval','A write interval ends before the read interval starts; the read must reflect the write or a later write.','The decisive relationship is completion before invocation. Overlapping intervals allow more than one legal ordering.') +
    section('2. Compare guarantees by their scope',`<p>Read-your-writes protects a session’s own completed changes. Monotonic reads prevent that session from going backward in a history. Eventual convergence asks copies to become consistent after updates stop and communication and repair succeed. Linearizability constrains all participating clients’ operations on the object, including the read from a shopper who never wrote.</p>`) +
    table('Promises answer different questions',['Promise','Question it answers'],[['Read-your-writes','Does my later read include my update?'],['Monotonic reads','Can my session go backward?'],['Eventual convergence','Can copies converge after updates stop?'],['Linearizability','Do operations look like one current object respecting completed calls?']]) +
    section('3. A check and an action are two operations',`<p>Two users check whether the name ann is free. Both reads return “free,” then both insert. Even if each read and write is linearizable by itself, the two-call sequence is not automatically one atomic operation. Use a single conditional operation, a uniqueness constraint at the authoritative write path, or an appropriate transaction to make “claim ann if free” indivisible.</p><p><b>Serializability</b> concerns whether transactions appear to run in some serial order. It does not by itself require that order to follow real-time completion. Strict serializability adds that requirement for transactions. Keep object-level operation guarantees and multi-record transaction guarantees explicit; using the same word “consistent” for all of them hides the needed mechanism.</p>`) +
    section('4. Fresh reads require current authority',`<p>Reading from a machine labeled leader is insufficient if it has been deposed but does not know it. A correct protocol must establish that the participant is still authorized for the relevant read, using its quorum/read protocol or a correctly implemented lease. The old participant’s local belief is not proof.</p><p>During a communication partition, a service preserving linearizable behavior cannot simply allow isolated sides to perform every conflicting operation successfully. Some operations must wait or fail when the authority needed by the protocol cannot be established. This is a specific failure trade-off, not a blanket instruction to rank “consistency” and “availability” under all healthy conditions.</p><p>Check guarantees using observed histories of calls and results, including overlap, timeouts and recovery. Average replication delay is not a substitute. Next we make authority concrete with paused workers, expiring leases and a storage gate that rejects obsolete actors.</p>`),
    check:'Both clients read “free” and then insert. Does linearizability of each individual call make the entire name claim atomic?',answer:'No. Another operation may occur between the check and the insert. Claiming the name requires one coordinated conditional operation or a transaction with the required constraint.',next:'Pauses, leases and fencing',
    source:{label:'Herlihy and Wing: Linearizability',href:'https://cs.brown.edu/~mph/HerlihyW90/p463-herlihy.pdf'},
    diagnose:[{t:'Fresh-looking reads permit a race',sym:'Two successful reads of “free” lead to two claims.',why:'A multi-call workflow was mistaken for an atomic conditional operation.',fix:['Move the condition into the authoritative write operation.','Verify the invariant under concurrent attempts.']}]
  });

  lesson({
    title:'Pauses, leases and fencing',phase:'Part IV · Coordination and recovery',before:'A timeout cannot prove a process is dead, clocks are imperfect, and a correct operation needs current authority.',goal:'Trace an obsolete worker resuming, distinguish lease expiry from write rejection, and place the fencing check at the resource.',
    problem:'Worker A owns a 10-second lease to update an order file. It pauses for 30 seconds. The lease service gives B a new lease, and B updates the file. A resumes with an old queued write and overwrites B’s work unless storage can reject it.',
    predict:{q:'Where must an obsolete write be rejected to protect the file?',opts:['Only in the old worker’s local lease check','At storage or another enforcing boundary for the effect','In a monitoring alert after the overwrite'],ans:1,why:'A worker can pause after checking, or a message can be delayed. The component applying the effect must enforce authority.'},
    explain:section('1. A process can stop making progress without dying',`<p>A <b>pause</b> can come from scheduling, garbage collection, a suspended machine or stalled execution. The process retains its memory and may continue later. Other participants observe missing messages, much like a crash. When A resumes, its local variables may still say it owns the file.</p><p>Even without a process pause, a write request can wait in a network queue. Revoking authority after the request was sent does not remove those bytes from every queue. Safety must hold when an old request finally reaches the resource.</p>`) +
    section('2. A lease gives time-limited permission',`<p>A <b>lease</b> grants a role or access for a duration under a specified protocol. The lease service can eventually give another participant permission after expiry. Renewal helps a healthy owner keep operating. Expiry helps recovery when it stops communicating.</p><p>Timing assumptions still matter: which clock measures the duration, what uncertainty is allowed, and when is the holder permitted to act? Checking a lease and then doing a write is two steps. A pause between them can invalidate the check before the effect happens. Rechecking merely moves the same window unless the enforcement and effect are coupled.</p>`) +
    figure('fencing-gate','Storage with highest accepted token 8 accepts B’s token 8 and rejects resumed A’s token 7.','The resource sees the stale token on the actual write, so a paused worker cannot bypass the check.') +
    section('3. Attach an increasing fencing token',`<p>A <b>fencing token</b> is an authority number issued in increasing order by a suitable coordination protocol. A holds 7; its successor B holds 8. Every write carries the token. Storage remembers the greatest accepted token and atomically rejects a write whose token is older.</p><pre>highest accepted token: 8\nwrite(token = 7, old contents) → reject\nwrite(token = 8, new contents) → accept</pre><p>The token is not a wall-clock timestamp generated independently by each worker. Its issuer must preserve the ordering and uniqueness required across failures. The storage check must be part of applying the write, not a separate unprotected read of the current token.</p>`) +
    section('4. State the remaining boundary',`<p>A simple highest-seen gate rejects 7 after storage has seen 8. It does not necessarily know a new token was issued before any request with that token arrives. Protocols needing immediate revocation must establish current authority at the resource more strongly. Describe the sequence rather than claiming any token mechanism solves every access policy.</p><p>Likewise, equal-token writes can still be duplicated or reordered. Fencing rejects obsolete owners; it does not supply payment idempotency, transaction isolation or all ordering within one owner’s work. Combine only the mechanisms the effect requires.</p><p>If an external resource cannot check tokens, a lease cannot by itself prevent every obsolete effect. Use an enforcing intermediary or an operation protocol the resource supports. For investigation, log holder identity, token, issue/renew events and accepted or rejected effects. Next we ask how several machines can maintain the authoritative sequence that issues roles and survives leader changes.</p>`),
    check:'A checks that its lease is valid, pauses, and writes after B takes over. Why does the check not help?',answer:'The check and effect are separated by the pause. Storage must atomically validate authority when applying the effect; A’s earlier belief is stale.',next:'Consensus: one committed history',
    diagnose:[{t:'The obsolete owner resumes',sym:'A later owner’s work is overwritten after a long pause.',why:'The effect trusted a worker-side lease check.',fix:['Carry ordered authority tokens on each effect.','Make rejection atomic at the resource enforcing the effect.']}]
  });

  lesson({
    title:'Consensus: one committed history',phase:'Part IV · Coordination and recovery',before:'You know ordered logs, replica progress, quorum overlap and obsolete authority. These are the ingredients of a safe shared decision history.',goal:'Separate leader election, log replication and commitment, and explain why a majority is useful only together with protocol rules.',
    problem:'Five nodes store which worker owns each shard. A network break leaves the old leader with one peer and three nodes on the other side. If both sides confirm a different owner for shard 8, the workers may both write. We need one accepted history across leadership changes.',
    predict:{q:'A five-voter group splits into sets of two and three. Which side can form a majority of the unchanged group?',opts:['Both sides, using their local size','The side with three voters','Neither; every operation needs all five'],ans:1,why:'A majority of five is three. The two-node side cannot shrink the membership by local declaration.'},
    explain:section('1. Agree on decisions, then apply them',`<p><b>Consensus</b> lets participants agree on a decision under a stated failure model. A replicated state machine extends this to an ordered sequence of decisions. The machines apply the agreed commands to their state. If the state transitions are deterministic and the input sequence is the same, the resulting state is the same.</p><p>For shard ownership the commands might be “assign shard 8 to A” followed by “assign shard 8 to B.” Our concern is a single committed sequence, even when the participant proposing commands changes. A temporary log entry is a proposal; it is not yet a promise that every future leader must preserve it.</p>`) +
    figure('raft-states','Follower becomes candidate on timeout; candidate becomes leader with a majority; a higher term causes step down.','Role changes follow protocol evidence. A timeout starts an election; it does not itself make a node leader.') +
    section('2. Understand the normal Raft path',`<p>Raft is one concrete protocol. Nodes have follower, candidate and leader roles. A <b>term</b> is a monotonically advancing protocol epoch. A follower lacking timely leader contact can become a candidate and request votes for a new term. Voting and log freshness rules constrain which candidate can win.</p><p>The leader appends a command, sends matching log entries to followers and tracks responses. For entries from its current term, replication to a majority allows it to advance the committed position under Raft’s rules. Entries before that position can then be applied. Commitment and application remain different steps, just as storage and application differed in the first replication lesson.</p>`) +
    section('3. Why intersection needs election rules',`<p>Any two majorities of the same fixed group intersect. This shared participant is useful only if it remembers and obeys the protocol’s rules. An arbitrary majority voting without durable state or log checks would not preserve the committed history.</p><p>Raft compares the last log term before the last log index when deciding whether a candidate is sufficiently up to date. A numerically longer log can be older in the sense the protocol cares about. The earlier failover ruler assumed compatible prefixes of one history; this election matrix shows why that assumption is too weak for general recovery.</p><p>Some uncommitted suffix entries may be replaced after a leadership change. The system must not return the promised committed success too early. Correct current-term commitment rules also matter when considering entries left by older leaders.</p>`) +
    section('4. Safety and progress are separate',`<p><b>Safety</b> means the protocol does not accept conflicting committed decisions. <b>Progress</b> means it can eventually make new decisions when its communication and timing conditions allow. A majority unable to communicate cannot keep completing coordinated writes. Stopping can preserve safety while reducing availability.</p><p>Changing membership needs a protocol that preserves the required overlap; simply recalculating majorities independently can create two authorities. Reads also need a suitable authority check. Neither an election winner nor a log copied to a majority automatically makes arbitrary follower reads linearizable.</p><p>The examples assume crash failures, not malicious voters. All timers and entry values are illustrative. In real deployments inspect term, voting membership, committed position and applied position separately. Next we coordinate one business action spanning several independent data owners.</p>`),
    check:'A log has more entries than B’s, but its last term is older. Does Raft always prefer A?',answer:'No. Raft’s freshness comparison checks the last term first, then the last index. Length alone is not the election rule.',next:'Atomic commit across data owners',
    source:{label:'Raft extended paper: election, replication and safety rules',href:'https://raft.github.io/raft.pdf'},
    diagnose:[{t:'Success is returned for an uncommitted entry',sym:'A confirmed ownership change disappears after an election.',why:'Local append or minority replication was mistaken for commitment.',fix:['Trace the commitment rule and voting configuration.','Return the promised success only after the required committed boundary.']}]
  });

  lesson({
    title:'Atomic commit across data owners',phase:'Part IV · Coordination and recovery',before:'Consensus preserves one decision history. Partitioning can place two accounts under different owners, each with its own local transaction.',goal:'Explain prepare and decision in two-phase commit, its blocking case, and how a recoverable workflow differs from atomic visibility.',
    problem:'A transfer removes 100 from account A on shard 1 and adds 100 to B on shard 2. The service stops after the debit. Both shards worked correctly in isolation, yet the overall transfer is incomplete. A pair of successful local transaction designs is not automatically one shared transaction.',
    predict:{q:'A participant voted prepared, but cannot learn whether the coordinator committed. Can it always safely abort on its own timeout?',opts:['Yes, because no reply means abort','No; a durable commit decision may already exist','Yes, because prepare changed no protocol state'],ans:1,why:'Another participant may have received a commit decision. The prepared participant must recover the decision according to the protocol.'},
    explain:section('1. Name the invariant',`<p><b>Atomic commit</b> means the participants in a transaction reach an all-commit or all-abort outcome. For the transfer, the intended outcome includes both debit and credit, or neither. Each shard’s local transaction protects its own changes; a coordinator must connect the outcomes.</p><p>This is a different problem from agreeing on a replicated command at one owner. Consensus can replicate a coordinator’s decisions, but atomic commit still has to involve the account participants and their ability to finish the transaction.</p>`) +
    section('2. First phase: prepare',`<p>In <b>two-phase commit</b>, abbreviated 2PC, a coordinator asks participants to prepare. Each checks whether it can commit its local part, acquires the necessary protection and durably records the prepared state before voting yes. A no vote prevents the all-commit outcome.</p><p>Prepared means the participant has promised it can finish if told to commit, while retaining enough recovery information if it crashes. It has not independently decided the global result. Some implementations hold locks or other resources while prepared, which can block unrelated work.</p>`) +
    table('Participant states need a durable decision',['State','Meaning','After losing contact'],[['Active','Doing local transaction work','Can fail before promising prepare'],['Prepared','Voted yes; waiting for global outcome','Recover decision; do not invent one'],['Committed','Commit decision applied','Retain enough recovery state'],['Aborted','Abort decision applied','Release protected resources']]) +
    section('3. Second phase: record and distribute a decision',`<p>If all required participants vote yes, the coordinator durably records commit before distributing it. Otherwise it follows the abort rules. Participants apply the decision and acknowledge it. Messages and participants may fail between each step, so the logs and transaction identity must support repeated recovery actions.</p><p>After preparation, a participant missing the decision cannot always distinguish “coordinator failed before deciding” from “commit was recorded and sent to another participant.” A timeout does not resolve this uncertainty. Classic 2PC can block until the decision becomes recoverable. A replicated coordinator reduces some failure cases, but cannot make every partition disappear.</p>`) +
    section('4. A workflow offers a different promise',`<p>Sometimes the business can expose a pending state and complete work later. A durable intent journal records transfer 7731 before applying steps. Each debit and credit uses that identity, making retries safe within the effect protocol. Reconciliation resumes incomplete work or takes defined compensating actions.</p><p>This is a <b>recoverable workflow</b>, not automatically an atomic transaction. An observer may see the debit before the credit unless another boundary hides partial states. A compensation is a new business action; it is not necessarily identical to rolling back an invisible database transaction.</p><p>A transactional outbox is another useful boundary: a local transaction stores both business state and an event to publish. A relay can retry publishing it. Consumers still need duplicate handling. Choose 2PC, local atomic boundaries or a workflow by the invariant and visibility requirement, rather than treating all retryable sequences as equivalent.</p><p>Monitor prepared age and pending workflow age. Both are unfinished work, but their recovery rules differ. Next we reuse identities, retries and commit boundaries for distributed batch tasks.</p>`),
    check:'A journal eventually completes both transfer steps. Did it necessarily hide the intermediate debit from readers?',answer:'No. Recoverability and atomic visibility are separate promises. Readers may observe pending or partial state unless the design explicitly prevents it.',next:'Batch processing: map, shuffle and reduce',
    source:{label:'PostgreSQL: prepared transactions and retained locks',href:'https://www.postgresql.org/docs/current/sql-prepare-transaction.html'},
    diagnose:[{t:'Prepared work blocks indefinitely',sym:'Transactions retain resources after coordinator contact is lost.',why:'A participant cannot safely invent the global outcome.',fix:['Recover the durable decision through the transaction protocol.','Inspect prepared age and coordinator durability; do not force an outcome from a timeout alone.']}]
  });

  lesson({
    title:'Batch processing: map, shuffle and reduce',phase:'Part V · Processing with the same building blocks',before:'Work can be split by key, messages can be retried, and incomplete effects need a visibility boundary.',goal:'Trace records through map, shuffle and reduce, explain skew, and separate a task attempt from its accepted output.',
    problem:'The marketplace needs yesterday’s revenue per city. The input is too large for one worker to finish before morning. Splitting the scan helps, but city totals still require related records to meet, and failed workers may leave partial output.',
    predict:{q:'Two map tasks emit (HCM, 10) and (HCM, 20). Where must those values meet to compute HCM’s total?',opts:['In the same reduce group for HCM','Only in the original map worker','Nowhere; adding workers combines them automatically'],ans:0,why:'The shuffle groups values by key so the reduction can combine the complete group.'},
    explain:section('1. Make the work explicit',`<p>A <b>batch</b> job processes a bounded input, such as a day of order records. The system divides that input into pieces assigned to tasks. A <b>map</b> task reads its piece and emits key/value pairs. For revenue by city the key is city and the value is an order’s amount.</p><p>Two workers can independently scan different input pieces. Their output is not yet a city total: each may have seen orders for the same city. The data must be regrouped by the reduction key. More workers help the independent scan, while grouping and final output still need their own mechanisms.</p>`) +
    figure('batch-shuffle','Two mappers send HCM values 10 and 20 to one reducer and Hanoi values 5 and 7 to another.','Follow records, not just machines: equal keys meet before a group result can be computed.') +
    section('2. Shuffle moves groups to their owner',`<p>The <b>shuffle</b> routes intermediate records so all values for one reduction key reach the responsible reducer. It can involve partitioning, sorting, buffering, network transfer and disk I/O. A <b>reduce</b> task combines its group: HCM gets 10 + 20 = 30; Hanoi gets 5 + 7 = 12.</p><p>This is data partitioning applied to computation. The chosen key defines what must meet. A query joining by seller and a query aggregating by city may require different redistributions even when the input files are identical.</p><p>For suitable functions, a local combiner can reduce traffic. Summing amounts locally before transfer is valid because partial sums can be added. Arbitrary averages cannot be combined by averaging averages unless the counts are also carried; the mathematical operation matters.</p>`) +
    section('3. A hot group becomes the slowest task',`<p>If most orders belong to one city, its reducer receives most work. This is <b>skew</b>. Equal numbers of tasks do not imply equal amounts of data or compute. The job’s completion time is often controlled by the final slow task.</p><p>For a decomposable sum, add a temporary bucket to the hot city key, compute partial totals in parallel, then combine those partial totals by city. This introduces another stage and is safe only when the reduction supports it. Merely adding reducers does not split a group whose key is unchanged.</p>`) +
    section('4. Retry attempts without accepting partial results',`<p>A logical task can have several <b>attempts</b>: one worker writes half its output and crashes; another attempt completes. If all attempts append to one shared final file, the failed partial output can be counted alongside the successful output.</p><p>Keep attempt output separate and let a commit protocol select the accepted result for each task. Other attempts are discarded or made invisible. The exact commit mechanism depends on storage; an atomic rename on one filesystem is not a universal object-storage transaction.</p><p>Task output handling does not automatically cover outside effects. A mapper sending payments still needs the payment identity protocol from the RPC lesson. Treat computation, accepted output and external effects as separate boundaries.</p><p>Inspect input bytes and shuffle bytes per task, attempt histories and accepted outputs. This connects the original bottleneck lesson to data placement and retries. Next we remove the fixed input end and process a continuing log of events.</p>`),
    check:'A failed task wrote half its result and a retry wrote the full result. Why is appending both to the final output wrong?',answer:'The logical task’s records can be duplicated. Publish one accepted attempt result, and prevent partial or losing attempts from contributing.',next:'Stream processing: offsets, state and event time',
    source:{label:'Google: MapReduce, grouping and fault-tolerant task execution',href:'https://research.google/pubs/mapreduce-simplified-data-processing-on-large-clusters/'},
    diagnose:[{t:'One reducer determines the whole job duration',sym:'Most tasks finish while one keeps shuffling and reducing.',why:'A hot key concentrates the work in one group.',fix:['Compare bytes and processing time by task and key.','Use partial aggregation or a valid two-stage reduction when the operation permits it.']}]
  });

  lesson({
    title:'Stream processing: offsets, state and event time',phase:'Part V · Processing with the same building blocks',before:'A task can be retried and its output needs a commit boundary. Physical time and logical order answer different questions.',goal:'Trace a consumer’s offset and effect across a crash, distinguish event time from processing time, and choose a late-data policy.',
    problem:'Orders arrive continuously. A consumer reads an event, updates a city total and records where it reached. A crash between those steps can skip or repeat an effect. Meanwhile an order sent from a disconnected phone arrives after the report window has closed.',
    predict:{q:'A consumer saves offset 52 before applying event 52, then crashes. If it restarts after 52, what is at risk?',opts:['Event 52’s effect is skipped','Event 52 is necessarily applied twice','Nothing; an offset performs the business update'],ans:0,why:'The stored progress says the event was handled, but its effect was not applied. Offset and effect were committed separately.'},
    explain:section('1. A stream has progress without a final end',`<p>A <b>stream</b> is a continuing sequence of events. A durable partitioned log retains events so consumers can read and replay them. An <b>offset</b> identifies a position within one log partition. It is not a timestamp or a global position across all partitions.</p><p>A <b>consumer</b> reads events and performs work. It may also keep <b>state</b>, such as revenue totals. Saving an offset records where the consumer believes processing has reached. In these examples “saved through 52” means restart begins after event 52; some systems instead store the next offset to read.</p>`) +
    table('Crash windows: offset and effect are separate writes',['Order of steps','Crash location','Risk'],[['Save progress, then effect','Between the steps','Skip the unapplied effect'],['Effect, then save progress','Between the steps','Replay and repeat the effect'],['One supported atomic boundary','Within recovery protocol','Restore a coordinated state']]) +
    section('2. Define the processing boundary',`<p>Saving progress first risks missed work. Applying the effect first risks repeated work after replay. At-least-once processing commonly chooses the latter and requires idempotent effects or a deduplication identity. An event’s logical identifier should survive replay even when the task attempt changes.</p><p>A supported transaction or checkpoint protocol can coordinate offsets and managed state. The guarantee applies within that boundary. A framework’s exactly-once state processing does not automatically make an unrelated external email, HTTP charge or database update exactly once. That destination must participate in a suitable transaction or provide an idempotent effect protocol.</p><p>Recovering state also needs the corresponding input progress. A total restored from one checkpoint and offsets restored from another can skip or repeat contributions. A checkpoint represents a defined recovery point, not just a copy of arbitrary local memory.</p>`) +
    section('3. Separate when an event happened from when it arrived',`<p><b>Event time</b> is the event’s claimed occurrence time. <b>Processing time</b> is when the consumer processes it. A phone event timestamped 12:01 may arrive at 12:05. Network delays, offline devices and clock errors make these times differ.</p><p>A <b>window</b> groups events for an interval, such as revenue from 12:00 to 12:02. If grouped by event time, the late phone event belongs in that earlier window. The processor must decide how long to wait and whether to revise an emitted result.</p>`) +
    section('4. A watermark is a progress policy',`<p>A <b>watermark</b> expresses the processor’s estimate or declared progress of event time according to its source and framework rules. It helps decide when to emit or retire a window. It is not universal proof that no earlier event can ever arrive. With multiple input partitions, combining their progress can leave a slow or idle input holding back results.</p><p>A late-data policy can discard late events, send them to another path, or keep window state for a bounded interval and emit corrections. Each choice changes the report’s meaning. Corrections need downstream handling, such as replacing a result by window identity rather than adding every emitted total.</p><p>Longer retention accepts more late events but uses more state. Faster initial reporting may produce provisional totals. Define the result contract, then monitor consumer lag, replay, checkpoint age and lateness. You have now reused the same foundations—messages, identities, copies, order and commit boundaries—from one remote call through distributed processing.</p>`),
    check:'A window first emits total 20 and later emits corrected total 25. Should a downstream report add them to get 45?',answer:'No, if the second emission replaces the same window result. Carry the window identity and update semantics; a correction is not necessarily another independent contribution.',next:'Review the journey',
    source:{label:'Kafka delivery semantics and the external-effect boundary',href:'https://kafka.apache.org/41/design/design/#message-delivery-semantics'},
    diagnose:[{t:'A replay repeats an external effect',sym:'A crash creates duplicate emails or payments despite restored stream state.',why:'The external effect was outside the offset/state commit boundary.',fix:['Trace the crash point relative to progress and effect.','Use a stable effect identity or a supported atomic destination protocol.']}]
  });
  // The last lesson returns to the foundation, rather than linking to a nonexistent chapter.
  chapters[14].explain = chapters[14].explain.replace('#ch15&view=explain', '#ch0&view=explain');
  window.COURSE = {
    name:'Distributed Systems',
    kick:'15 chapters · foundations to coordination and processing',
    lead:'Follow one marketplace from a single machine to cooperating processes, replicated and partitioned data, safe coordination, and batch and stream processing. Each lesson introduces its vocabulary before using it in a failure. Read the explanation first, then use the selected visual to trace the mechanism.',
    chapters
  };
})();
