services:
  scylla:
    image: scylladb/scylla:6.2
    command: --smp 1 --memory 1G --overprovisioned 1
    ports:
      - "9042:9042"
      - "9180:9180"
    volumes:
      - scylla-data:/var/lib/scylla

volumes:
  scylla-data:
