#!/usr/bin/env python3
"""Build data/tech-index.js, the search index behind the site.

Reads data/systems.js and every tour in techstack/<system>/*.html, and emits one entry per tour plus one per chapter
(title + the chapter's question/principle/design text, deep-linked as <tour>.html#chN).
Usage: python3 tools/build_site_index.py
"""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STR = r"'((?:[^'\\]|\\.)*)'"

def load_systems():
    src = open(os.path.join(ROOT, 'data/systems.js'), encoding='utf-8').read()
    body = src[src.index('['):src.rindex(']') + 1]
    body = re.sub(r'([{,]\s*)([A-Za-z_]\w*)\s*:', r'\1"\2":', body)
    body = re.sub(STR, lambda m: json.dumps(m.group(1).replace("\\'", "'")), body)
    return json.loads(body)

def clean(s):
    s = s.replace("\\'", "'").replace('\\\\', '\\').replace('\\n', ' ')
    s = re.sub(r'<[^>]+>', '', s)
    s = s.replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&')
    return re.sub(r'\s+', ' ', s).strip()

def chapters(html):
    phases = re.search(r'const PHASES=\[(.*?)\n\];', html, re.S)
    ph = re.findall(r"\{t:" + STR + r"(?:,live:true)?,s:" + STR, phases.group(1)) if phases else []
    out = []
    for m in re.finditer(r"\{ask:" + STR + r",\s*why:" + STR, html):
        tail = html[m.end():m.end() + 6000]
        def f(k):
            x = re.search(r'\b' + k + r":" + STR, tail); return clean(x.group(1)) if x else ''
        v0 = re.search(r"v0:\{name:" + STR, tail)
        out.append(dict(ask=clean(m.group(1)), why=clean(m.group(2)), principle=f('principle'), design=f('design'), v0=clean(v0.group(1)) if v0 else ''))
    return ph, out

def main():
    systems = load_systems(); out = []
    for s in systems:
        out.append(dict(type='Tour', system=s['id'], title=s['name'] + ' internals, end to end',
                        summary=s['problem'], body=s['topics'], url=s['url'], tags=['tour', 'interactive']))
        path = os.path.join(ROOT, s['url'])
        if not os.path.exists(path): print('missing tour', s['url']); continue
        ph, ch = chapters(open(path, encoding='utf-8').read())
        for i, c in enumerate(ch):
            t, sub = (ph[i] if i < len(ph) else ('Chapter %d' % (i + 1), ''))
            out.append(dict(type='Chapter', system=s['id'], title=f"{s['name']} · {i + 1}. {clean(t)}",
                            summary=c['ask'], body=' '.join([clean(sub), c['why'], c['v0'], c['principle'], c['design']]),
                            url=f"{s['url']}#ch{i}", tags=[w for w in re.split(r'[\s·]+', clean(sub).lower()) if len(w) > 2]))
    for i, e in enumerate(out): e['id'] = i
    js = '/* generated by tools/build_site_index.py: do not edit */\nwindow.SITE_TECH_INDEX = ' + json.dumps(out, ensure_ascii=False, indent=0) + ';\n'
    open(os.path.join(ROOT, 'data/tech-index.js'), 'w', encoding='utf-8').write(js)
    by = {}
    for e in out: by[e['type']] = by.get(e['type'], 0) + 1
    print(len(out), 'entries', by)

main()
